### ISSUE TITLE
SDL does not unsubscribe mobile app and does not sends UnsubscribeWayPoints to mobile app

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2478] opened 2018-07-31 12:39 UTC
### Bug Report
SDL does not unsubscribe mobile app and does not sends UnsubscribeWayPoints to mobile app

#### Descroption:
Currently when the application is unregistered,
UnsubscribeAppFromWayPoints() function is not called.
This is because the call is done in
UnSubscribeWayPointsRequest::on_event(),
but to call this event SDL must receive UnSubscribeWayPointsRequest
from the mobile application. In our case when we have
UnregisterApplication call UnsubscribeAppFromWayPoints is omitted.

##### Expected Behavior
SDL does unsubscribe mobile app and sends UnsubscribeWayPoints to mobile app

##### Observed Behavior
SDL does not unsubscribe mobile app and does not sends UnsubscribeWayPoints to mobile app

##### OS & Version Information
* OS/Version:
* SDL Core Version: 
* Testing Against:

**Comment by LitvinenkoIra** [comment] 2018-08-30 11:28
duplicate of #2461

**Closed by LitvinenkoIra** 2018-08-30 11:28 UTC
Labels: Bug, Contributor priority 1: High
