### ISSUE TITLE
SDL must start PTU for any app except navi right after app successfully request to start first secure service

### ISSUE THREAD

**Issue by AStasiuk** [smartdevicelink/sdl_core#1924] opened 2017-11-24 13:42 UTC
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register non-navi mobile application
5. PTU for new application without certificate is performed
6. Start secure RPC(7) service 

## Actual result
SDL does not start PTU after starting secure service.

## Expected result
1. SDL starts PolicyTableUpdate process on sending SDL.OnStatusUpdate(UPDATE_NEEDED) to HMI to get "certificate" right after application successfully requests to start first secure service.
2. SDL does not respond to StartService_request from mobile application till PTU is not finished.

## Test scripts
[1924_1_non-navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1924_1_non-navi.lua)
[1924_2_navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1924_2_navi.lua)

## Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by dboltovskyi** [comment] 2017-12-01 12:15
Priority was set to High. Issue makes impossible starting of secure sessions because of absent certificate in PT. TLS handshake will not be resumed until valid certificate will be received.

**Comment by dboltovskyi** [comment] 2017-12-27 12:57
Issue is reproduced on develop branch (0b19cf4)

**Comment by jacobkeeler** [comment] 2018-01-31 15:43
Verified that this is fixed by #1971.

One thing to note is that the tests fail in the `Clean Environment` step after a successful run, but I suspect this is an issue with the test scripts themselves.

**Comment by jacobkeeler** [comment] 2018-01-31 19:08
[Test 1](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1924_1_non-navi.lua) fails on occasion, looks to be a timing issue

**Comment by jacobkeeler** [comment] 2018-01-31 21:11
Fixed with the merge of #1971

**Closed by jacobkeeler** 2018-01-31 21:11 UTC
Labels: Bug, Contributor priority 1: High
