### ISSUE TITLE
SDL Crash - After all apps exited

### ISSUE THREAD

**Issue by AByzhynar** [smartdevicelink/sdl_core#3108] opened 2019-10-31 11:07 UTC
### Bug Report
SDL crashes after all apps exited.

##### Occurence
Once

##### Precondition
1. HMI and SDL are started
2. Two apps are registered and activated 

##### Reproduction Steps
Unknown. 
SDL core crash happens during manual testing of RC Multiple Modules functionality.
2 app instances were involved.
After exiting of the last app (via Menu->Exit) - in 2-3 seconds SDL crashed.

##### Expected Behavior
SDL works normally without crashes

##### Observed Behavior
SDL crashed 

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/6.0.0_RC2 ( 4d283e )
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop ( bd53f1 ) 
* SPT: SyncProxyTester ( 20191028 Nightly-Android, Proxy Lib Ver 4.9.1 ) 

##### Attachments:
  - gdb: [gdb.txt](https://github.com/smartdevicelink/sdl_core/files/3793440/gdb.txt)
  - logs: N/A

**Comment by AByzhynar** [comment] 2019-10-31 11:12
After issue back trace analysis - the crash reason is clear. During OnSystemCapabilityUpdated notification - app was not possible to extract required extension. Thus DCHECK (ASSERT) happens. But it is unclear how an extension could be absent.

**Comment by dboltovskyi** [comment] 2019-10-31 14:50
Since the issue is happened only once it doesn't know whether it regression one or not.
Additional analysis is required.

**Comment by dboltovskyi** [comment] 2019-10-31 15:02
@theresalech Please triage this issue.

**Comment by theresalech** [comment] 2019-10-31 15:09
@dboltovskyi please let us know once your additional analysis is complete, and we'll review.  Thanks!

**Comment by LitvinenkoIra** [comment] 2019-11-01 13:47
@AByzhynar it seems like the same crash was reproduces on my side. Please check the attached logs 
[2019-11-01_15-40-30.zip](https://github.com/smartdevicelink/sdl_core/files/3798160/2019-11-01_15-40-30.zip)

**Comment by theresalech** [comment] 2019-11-06 14:49
@LitvinenkoIra @AByzhynar @IGapchuk are you still investigating this issue? Do you have plans to submit a fix for Livio review?

**Comment by IGapchuk** [comment] 2019-11-06 14:59
@theresalech We have finished the investigation and prepared a fix for it and the fix now under testing. We'll provide PR with the fix as quickly as possible after successful testing.

**Comment by JackLivio** [comment] 2019-11-21 19:18
Fixed with merge of #3115

**Closed** 2019-11-21 19:18 UTC
