### ISSUE TITLE
Revise SDL-0122 to exclude synonyms

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_core#2539] opened 2018-08-27 13:34 UTC
Altered Proposal: [SDL-0122 Handling VR help requests when application does not send VR help prompt](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0122-New_rules_for_providing_VRHelpItems_VRHelpTitle.md)

> When the user asks for "help" regarding an application, the help prompt that is played and the help menu that is displayed for that application is based on the information provided by the application through the SetGlobalProperties RPC.
> Through this proposal we propose a mechanism for handling "help" requests by the user when the application does not provide any such information.

Review: https://github.com/smartdevicelink/sdl_evolution/pull/585

**Comment by theresalech** [comment] 2018-08-31 13:55
Closing as duplicate of #2154

**Closed by theresalech** 2018-08-31 13:55 UTC
Labels: proposal
