### ISSUE TITLE
App is disconnected due to PROTOCOL_VIOLATION when start audio streaming after rejected 2 times then accepted

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1004] opened 2016-11-07 17:42 UTC
## Occurrence
Always.

## Preconditions
1. SDL is started.
2. HMI is started.

## Steps to reproduce
1. Register Navi App
2. Activate App
3. Press "Audio Service - Show" button
4. Press "Start Service"
5. Press "Cancel" on popup
6. Press "Cancel" on popup
7. Press "Ok" popup
8. Press "Start File Streaming"

## Expected result
Audio Streaming is started.

## Actual result
App is unregistered with reason "PROTOCOL_VIOLATION".

# Environment
SDL repo: https://github.com/smartdevicelink/sdl_core.git
SDL branch: master
SDL commit: a6c32b4
HMI: https://github.com/LuxoftSDL/sdl_hmi: 01cb5b49883ed6288e34fcf7db24fd0439d08312
OS: Ubuntu 14.04 LTS

# Attachments
[att_issue#1004.zip](https://github.com/smartdevicelink/sdl_core/files/576163/att_issue.1004.zip).

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by jacobkeeler** [comment] 2017-11-07 18:54
@KhrystynaDubovyk @LuxoftAKutsan Looks like this issue still exists, but it may be related to the HMI.

When a `StartService(AUDIO)` is send to Core, it begins sending StartAudioStream once every second until a response is received from the HMI. This makes the HMI open several copies of the same "Would you like to start Audio Stream?" pop up on top of each other. If the user responds with `Cancel` to the first pop up, then responds with `Ok` of the other pop ups, then Core will receive a `failed` response followed by a `success` response. This is what seems to cause the `PROTOCOL_VIOLATION` message. Core should likely not be receiving several `StartAudioStream` responses.

Considering I haven't found any requirement/diagram where Core should be sending multiple `StartAudioStream` messages, I'm inclined to think this is an issue with Core, despite the fact that this behavior seems intentional.

**Comment by dboltovskyi** [comment] 2017-11-09 16:13
@jacobkeeler Please find diagram:
![issue_1004_diagram_1](https://user-images.githubusercontent.com/22884509/32615900-9cf40a1e-c579-11e7-9d94-fead46f81c7a.png)

**Comment by LuxoftAKutsan** [comment] 2017-11-13 18:14
@jacobkeeler issue is not reproduced in develop in the same sequence as it described ( implicitly partially fixed). 
But main root cause is still exist in SDL and will be fixed.

**Comment by jacobkeeler** [comment] 2017-11-22 16:53
Closed with the merge of #1855

**Closed by jacobkeeler** 2017-11-22 16:53 UTC
Labels: Bug
