### ISSUE TITLE
CCB: fix UpdateDeviceList conten

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#974] opened 2016-11-07 15:53 UTC
### Bug Report
SDL sends UpdateDeviceList with disconnected device in the deviceList 

##### Reproduction Steps
1. Connect several devices.
2. Disconnect devices
3. Initiate sending UpdateDeviceList from SDL

##### Expected Behavior
SDL sends UpdateDeviceList without disconnected devices.

##### Observed Behavior
Disconnected devices are presented in UpdateDeviceList

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: fa05b5f5b1af6fae7d684a5cc156ec2e68dbc197
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [att_issue#974.zip](https://github.com/smartdevicelink/sdl_core/files/575833/att_issue.974.zip)

**Comment by LitvinenkoIra** [comment] 2017-12-01 12:53
Priority Medium.
Loss of functionality on SDL side with standard use-case.

**Comment by LitvinenkoIra** [comment] 2019-12-10 14:21
Defect is reproduced.
SDL branch: develop(e137556)
ATF: develop
Script: smartdevicelink/sdl_atf_test_scripts#1919

**Comment by LitvinenkoIra** [comment] 2019-12-10 14:21
https://github.com/smartdevicelink/sdl_core/pull/2249 - rebased to the latest develop
Fix is valid

**Comment by LitvinenkoIra** [comment] 2019-12-13 12:57
Need to rework the fix due to regression 

The following aft test scripts failed: 
./test_scripts/iAP2TransportSwitch/001_happy_path.lua 
./test_scripts/iAP2TransportSwitch/002_resume_failed_simple_case.lua
./test_scripts/iAP2TransportSwitch/003_resume_failed_remove_data_check.lua 
./test_scripts/iAP2TransportSwitch/004_commands_hold_while_switching.lua

SDL: https://github.com/Ypostolov/sdl_core/tree/fix/fix/update_device_list bba0d8d9
Scripts: develop 6f43bfd
ATF: develop 37da7aba

**Comment by iCollin** [comment] 2020-01-22 14:36
> Need to rework the fix due to regression
> 
> The following aft test scripts failed:
> ./test_scripts/iAP2TransportSwitch/001_happy_path.lua
> ./test_scripts/iAP2TransportSwitch/002_resume_failed_simple_case.lua
> ./test_scripts/iAP2TransportSwitch/003_resume_failed_remove_data_check.lua
> ./test_scripts/iAP2TransportSwitch/004_commands_hold_while_switching.lua
> 
> SDL: https://github.com/Ypostolov/sdl_core/tree/fix/fix/update_device_list [bba0d8d](https://github.com/smartdevicelink/sdl_core/commit/bba0d8d9c8be1e2f600a3f0b336a39a25faee3ed)
> Scripts: develop 6f43bfd
> ATF: develop 37da7aba

I see these passing, they require `-DBUILD_TESTS=ON`.

Closed via #2249

**Closed by iCollin** 2020-01-22 14:36 UTC
Labels: Bug, Sync4-CCB
