### ISSUE TITLE
PolicyTableUpdate is valid and brings "certificate"

### ISSUE THREAD

**Issue by AStasiuk** [smartdevicelink/sdl_core#1888] opened 2017-11-23 15:04 UTC
**Occurrence: Always** 

# Description
SDL behavior in case no "certificate" in "module_config" section of Policy Table and PolicyTableUpdate is valid and brings "certificate" at "module_config" section and app sends StartService (<any_serviceType>, encypted=true) to SDL

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register mobile application
5. PTU is successful performed, PT has certificate
6. Activate App
7. Start secure audio/video/RPC service

## Expected result
1. SDL starts TLSHandshake sequence (by sending TLS Hello to this mobile app).
2. After successful TLSHandshake SDL sends StartServiceACK(encrypted=true) to mobile application and starts secure service. 

## Actual result
SDL does not start TLSHandshake, sends StartServiceACK(encrypted=false) to mobile application and does not start secure service. 

## Test scripts
[1888_1_navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1888_1_navi.lua)
[1888_2_non-navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1888_2_non-navi.lua)
[1888_3_navi_audio_force_off.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1888_3_navi_audio_force_off.lua)
[1888_4_navi_video_force_off.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1888_4_navi_video_force_off.lua)
[1888_5_navi_audio_force_on.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1888_5_navi_audio_force_on.lua)
[1888_6_navi_video_force_on.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1888_6_navi_video_force_on.lua)

## Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment] 2017-12-01 12:17
Contributor priority is set `High` with reason: The issue is related to secure service start logic.

**Comment by dboltovskyi** [comment] 2017-12-27 12:56
Issue is reproduced on develop branch (0b19cf4)

**Comment by jacobkeeler** [comment] 2018-01-31 20:04
Verified that this is fixed by #1971.

**Comment by jacobkeeler** [comment] 2018-01-31 21:10
Fixed with the merge of #1971

**Closed by jacobkeeler** 2018-01-31 21:10 UTC
Labels: Bug, Contributor priority 1: High
