### ISSUE TITLE
SDL miss "spaceAvailable"(mandatory) param in PutFile response

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1609] opened 2017-06-14 09:18 UTC
Environment:
OS: Ubuntu 16.04.
ARC: PC (x86)
SDL - Tag 4.2.1 commit e98cef9
Occurrence:
Always
Preconditions:
SDL is running and HMI is connected to SDL
Steps to reproduce:
Register any application with SDL
Send UnregisterAppInterdace
Send PutFile request => APPLICATION_NOT_REGISTERED Result code from SDL
*Actual result:*
SDL miss "spaceAvailable"(mandatory) param in PutFile response
[SDL_log.txt](https://github.com/smartdevicelink/sdl_core/files/1074100/SDL_log.txt)

*Expected result:*
"spaceAvailable"(mandatory) param present in PutFile response
Requirements: MOBILE_API.xml

**Comment by jacobkeeler** [comment] 2018-03-08 16:22
Duplicate of #1218

**Closed by jacobkeeler** 2018-03-08 16:22 UTC
Labels: best practice, documentation
