### ISSUE TITLE
Core dump during the USB device reconnection

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3345] opened 2020-04-28 10:19 UTC
### Bug Report
Core dump during the USB device reconnection

### Occurrences
1/80

##### Reproduction Steps
1. HMI and SDL are started
2. 3 mobile apps are registered via USB
3. Perform USB reconnection 

##### Observed Behavior
SDL crashes during the apps reconnection with the message 
> smartDeviceLinkCore: /home/jenkins/workspace/Release_6.1_SDL_NoUT_P/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/extensions/system_capability_app_extension.cc:91: static sdl_rpc_plugin::SystemCapabilityAppExtension& sdl_rpc_plugin::SystemCapabilityAppExtension::ExtractExtension(application_manager::Application&): Assertion `(ext_ptr)' failed.

##### Expected Behavior
All apps are registered successfully 

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC2
* HMI:https://github.com/smartdevicelink/sdl_hmi/commit/7a7e6acddc12b8b4e9d2b98df9c09ee423f6356d
* Transport: USB

##### Logs
[bt_core_dump_during_reconnection.zip](https://github.com/smartdevicelink/sdl_core/files/4544976/bt_core_dump_during_reconnection.zip)
[SmartDeviceLinkCore_dump.zip](https://github.com/smartdevicelink/sdl_core/files/4544978/SmartDeviceLinkCore_dump.zip)
[SmartDeviceLinkCore_dump_2.zip](https://github.com/smartdevicelink/sdl_core/files/4544980/SmartDeviceLinkCore_dump_2.zip)

**Comment by AKalinich-Luxoft** [comment] 2020-11-24 16:21
Closed as not actual as the root cause of that core dump has been addressed in #3475 (particularly, in [this](https://github.com/smartdevicelink/sdl_core/pull/3475/commits/7a433a38d37a6affbba48b954ee09b56a52bdfd4) commit)

**Closed by AKalinich-Luxoft** 2020-11-24 16:21 UTC
