### ISSUE TITLE
SDL must restore AddCommands in the same order as they were created by mobile app

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2389] opened 2018-07-18 12:14 UTC
### Bug Report
SDL must restore AddCommands in the same order as they were created by mobile app

##### Reproduction Steps
1. In case
SDL receives AddCommand from mobile app (UI+VR, only UI, only VR)

##### Expected Behavior
SDL must:
generate <internal_consecutiveNumber>
assign this <internal_consecutiveNumber> to each AddCommand requested by app
restore AddCommand by this <internal_consecutiveNumber> during data resumption (meaning: SDL must send UI.AddCommands to HMI by <internal_consecutiveNumber> one by one from resumption list)

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by LitvinenkoIra** [comment] 2018-08-10 14:31
duplicate of https://github.com/smartdevicelink/sdl_core/issues/1878

**Closed by LitvinenkoIra** 2018-08-10 14:31 UTC
Labels: Bug, Contributor priority 3: Low
