### ISSUE TITLE
CCB: Update LastState dictionary usages in resumption

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2465] opened 2018-07-30 13:41 UTC
### Bug Report
Needed implemented LastStateWrapper class for providing exclusive thread safe access to LastState instance from all places in the program.

##### Linked issues from CCB list
1. Fix potential mutex deadlocks in resumption storage
2. Fix deadlock while terminating 
3. LastState refactoring 

##### Description: 
Needed implemented LastStateWrapper class for providing exclusive thread-safe access to LastState instance from all places in the program. Needed replaced with LastStateWrapper object to avoid direct access to LastState instance from other components. 

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)
* Testing Against: ATF

##### BackTrace and Core file: 
[core.tar.gz](https://github.com/smartdevicelink/sdl_core/files/3819142/core.tar.gz)
[GdbBackTrace.txt](https://github.com/smartdevicelink/sdl_core/files/3819143/GdbBackTrace.txt)

**Comment by LitvinenkoIra** [comment] 2018-11-08 08:37
This is an improvement of existing functionality. Last state component is used during resumption. So for testing use 
https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop/test_scripts/Smoke/Resumption

**Comment by AByzhynar** [comment] 2019-11-07 10:42
The issue is being reproduced on current develop branch 891497bc9fb23434242dbe92e1f13dd1273fcb21
when running Transport Manager unit tests related to resumption. After analysis of backtrace - it is definitely a problem in SDL core code but not in unit tests. New backtrace and core file are attached to issue description.

**Comment by AByzhynar** [comment] 2019-11-12 15:42
@theresalech @JackLivio 

Please triage the issue for further implementation
This issue potentially affects every resumption flow. 

#### Details: 
SDL Core is a multithreading application - it requires many threads in order to perform many operations simultaneously.
In the current implementation, SDL uses lots of different threads to handle resumption flow. 
Every resuming application is a separate thread. Application backup is also a separate thread. 
The Resumption functionality uses such an entity as `Last State` - it is the last valid known application state which should be restored during application resumption. This is one of the most important resumption parts.
All resumption threads can use this `Last State` for applications backing up and restoring. Applications backup and restoring of other applications can be performed at the same time.
At this moment access to `Last State` is not synchronized between multiple threads. 
Thus different threads can perform reading/writing/removing etc on this entity at the same time. 
This leads to  SDL core occasional crashes. 
So the **threads exclusive access wrapper** for the Last State should be implemented.

**P.S.** Pull Request with the fix is ready but needs to be actualized and checked according to the current develop changes.

**Comment by theresalech** [comment] 2019-11-12 17:06
@AByzhynar please advise when the PR has been actualized and checked according to the current develop changes, and we'll review then, thank you!

**Comment by theresalech** [comment] 2020-02-17 15:23
Closed via #2626

**Closed by theresalech** 2020-02-17 15:23 UTC
Labels: Bug, Sync4-CCB
