### ISSUE TITLE
SDL creates redundant device_consent table in Policy DB

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#986] opened 2016-11-07 16:27 UTC
## Occurrence
Always.

## Preconditions
1. Core, HMI started 1st time.

## Steps to reproduce
1. Register App.

## Actual result
SDL do not add all device related info to Policy DB

## Expected result
SDL should add all device related info to Policy DB (according to dictionary identifier should be present)

# Environment
SDL branch: master
SDL commit: a6c32b4
HMI: HTML5
OS: Ubuntu 14.04 LTS
Transport: WiFi
Mobile device: HTC One
Mobile OS: Android 4.3
Mobile App version: SPT v.2.1.81 Code: 239
Mobile App type (media/non-media/navi/any): any

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by JackLivio** [comment] 2017-04-18 19:28
@KhrystynaDubovyk Do you know if this bug still exists or was fixed in the recent policies release?

**Comment by KhrystynaDubovyk** [comment] 2017-04-19 06:29
@Itileda 
Igor is this bug fixed?

**Comment by dcherniev** [comment] 2017-05-16 14:43
@JackLivio Checked this issue on the head of the develop branch, the device identifier is present in Policy DB, so this issue no longer occurs.
Checked on SDL commit: 458fa67468b2c10a7f8eb18277a83eb90c2f8004

**Comment by JackLivio** [comment] 2017-11-07 16:04
@KhrystynaDubovyk  @dcherniev When using an Sqlite Browser to examine the policy db after connecting an app and then  performing an ignition cycle, I see the the device identifier is present but all of the device fields are empty.

**Comment by JackLivio** [comment] 2017-11-07 16:08
Also is this issue for saving Device info or Device Consent groups? The title does not match the issue description. The title says there is redundant info saved, but the description says that no info is saved.

**Comment by dboltovskyi** [comment] 2017-11-20 10:10
@JackLivio 
Since the issue is quite old names of the tables has changed. Actual ones are "device" and "device_consent_group".
Both are related to device consent functionality and External Proprietary flow.

If SDL is built in default (PROPRIETARY) mode these ones are almost empty after app registration.
But if SDL is built in EXTERNAL_PROPRIETARY mode, and new app registered, tables became populated with appropriate data.

So for now this issue is not actual.

**Comment by LuxoftAKutsan** [comment] 2017-11-20 14:19
@JackLivio root cause of this defect is the same as in #1007. So it is not actual any more

**Closed** 2017-11-20 15:42 UTC
Labels: Bug
