### ISSUE TITLE
SDL doesn't send OnHMIStatus(FULL) to the non-media App if OnEventChanged(AUDIO_SOURCE:true) was before.

### ISSUE THREAD

**Issue by Itileda** [smartdevicelink/sdl_core#2612] opened 2018-09-14 12:27 UTC
### Bug Report
SDL doesn't send OnHMIStatus(FULL) to the non-media App if OnEventChanged(AUDIO_SOURCE:true) was before.

##### Reproduction Steps
1. Consent device
2. Send from HMI OnEventChanged(AUDIO_SOURCE:true)
3. Register non-media App

##### Steps
1. Activate App
##### Expected Behavior
SDL activates App, sends FULL notification

##### Observed Behavior
SDL doesn't send FULL to the App

##### OS & Version Information
* OS/Version: [The OS/Version you were running when the bug occurred]
* SDL Core Version: [The version of SDL Core you were using when the bug occurred]
* Testing Against: [What you tested with to observe this behavior. Proxy, App, HMI etc.]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by HSavynetska** [comment] 2019-11-26 16:09
The issue is relevant on the current develop branch

Environment:
 Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2064
 SDL build: [https://github.com/smartdevicelink/sdl_core/tree/develop] ( 891497b )
 ATF: develop branch

**Comment by dboltovskyi** [comment] 2020-06-15 20:53
Issue is very similar to https://github.com/smartdevicelink/sdl_core/issues/1908

**Comment by jacobkeeler** [comment] 2020-07-27 18:36
Closing as duplicate of #1908

**Closed by jacobkeeler** 2020-07-27 18:36 UTC
Labels: Bug
