### ISSUE TITLE
Policy table corruption after ign cycle (1587101)

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2598] opened 2018-09-10 14:21 UTC
### Bug Report
Policy table corruption after ign cycle (1587101)

##### Expected Behavior
AppLink; Policy table corruption after ign cycle (1587101)

##### OS & Version Information
* OS/Version: 
* SDL Core Version: 
* Testing Against:

**Comment by jacobkeeler** [comment] 2018-09-20 20:47
Duplicate of #2467

**Closed by jacobkeeler** 2018-09-20 20:47 UTC
Labels: Bug, Contributor priority 1: High
