### ISSUE TITLE
[SDLOPEN] SDL doesn't check result codes of HMI IsReady response

### ISSUE THREAD

**Issue by istoimenova** [smartdevicelink/sdl_core#1384] opened 2017-03-20 12:58 UTC
## Description:
SDL doesn't check result codes of HMI IsReady response

## Preconditions
SDL and HMI are started.

## Steps to reproduce
At InitHMI_OnReady send IsReady response with (<<error_result_code>>, available = true)

## Actual result
SDL accepts only available = true and interface is avalable, SDL doesn't check error_result_code

## Expected result
SDL should accept interface if is NOT available

## Environment
SDL repo: https://github.com/smartdevicelink/sdl_core/tree/feature/extended_policy_functionality
SDL commit: 7bd5326e8a6f5127220bf938a5be3063bdbb4ab4
OS with SDL: Ubuntu 14.04
VM used for OS with SDL (yes/no): no
ATF version: aa5beae6ab1726a9b43ed2fa15f66c20d7f7883f
Transport: WiFi

## Attachments
Problem can be reproduced with scripts:
https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/feature/extended_policy_functionality/test_scripts/API/IsReady/UI_IsReady/ATF_UI_IsReady_available_false_RAI.lua
https://github.com/CustomSDL/sdl_atf_test_scripts/blob/OS_DRAFT/test_scripts/API/IsReady/VR_IsReady/ATF_VR_IsReady_available_false_RAI.lua
https://github.com/CustomSDL/sdl_atf_test_scripts/blob/OS_DRAFT/test_scripts/API/IsReady/VR_IsReady/ATF_VR_IsReady_available_false_SingleRPC.lua

[Uploading ATF_VR_IsReady_available_false_RAI.lua.zip…]()

## Links
Requirements:
[UI Interface] SDL behavior in case HMI does not respond to UI.IsReady_request
[RegisterAppInterface] SDL behavior in case HMI does NOT respond to IsReady request
[UI Interface] HMI does NOT respond to IsReady and mobile app sends RPC that must be splitted

Clarification: Does SDL consider case VR.IsReady response with errorCode is the same as case VR.IsReady is not responded

## Expected delivery
- [ ]  Source code updates
- [ ]  Code comments
- [ ]  UTs add/update
- [ ]  ATF tests add/update
- [ ]  Manual tests
- [ ]  Add/update CI plans/jobs
- [ ]  SDD updates
- [ ]  Guidelines update (sdl_core_guides)
- [ ]  Guidelines update (sdl_hmi_integration_guidelines)

**Comment by aderiabin** [comment] 2017-12-01 12:53
Contributor priority is set `Medium` with reason: The issue is related to functionality: correctness of result code in response from HMI/SDL

**Comment by ValeriiMalkov** [comment] 2018-07-17 12:02
Questions of this issue: 
[Question #2374](https://github.com/smartdevicelink/sdl_core/issues/2374)

**Comment by jacobkeeler** [comment] 2020-08-24 16:28
Closing with the merge of #3433

**Closed by jacobkeeler** 2020-08-24 16:28 UTC
Labels: Bug
