### ISSUE TITLE
HMI sends request with String param with invalid characters

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2347] opened 2018-07-13 07:15 UTC
### Bug Report
HMI sends request with String param with invalid characters.

##### Reproduction Steps

HMI sends *request to SDL (please see list of impacted RPCs below) and this request has at least one String param with '\n' and/or '\t' and/or 'whitespace' as the only symbol(s).

##### Expected Behavior
Log corresponding error internally respond with 'INVALID_DATA' to HMI.

List of impacted RPCs:

1. SDL.GetDeviceConnectionStatus
2. SDL.ActivateApp
3. SDL.GetUserFriendlyMessage
4. SDL.GetListOfPermissions
5. SDL.UpdateSDL
6. SDL.GetStatusUpdate
7. SDL.GetURLs

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)
* Testing Against: ATF

##### Attach

**Comment by dboltovskyi** [comment] 2018-11-12 10:18
This issue closed since it's duplicate of https://github.com/smartdevicelink/sdl_core/issues/1862

**Closed by dboltovskyi** 2018-11-12 10:18 UTC
Labels: Bug
