### ISSUE TITLE
CCB: SDL restores AddCommands in the order they were created 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#1878] opened 2017-11-23 12:31 UTC
### Bug Report
SDL must restore AddCommands in the same order as they were created by mobile app

##### Reproduction Steps
1.  App successfully added some AddCommands (UI+VR, only UI, only VR)
2.  Ignition Off -> Ignition On
3.  App registers -> SDL successfully performs HMILevel resumption and data resumption 

##### Expected Behavior
The order of resumed AddCommands must be the same as order being before resumption.
- SDL must generate <internal_consecutiveNumber>
- assign this <internal_consecutiveNumber> to each AddCommand requested by app,
- restore AddCommand by this <internal_consecutiveNumber> during data resumption (meaning: SDL must send UI.AddCommands to HMI by <internal_consecutiveNumber> one by one from resumption list)

##### Observed Behavior
The order of resumed AddCommands is different from order being before resumption 

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)
* Testing Against: ATF

**Comment by aderiabin** [comment] 2017-12-01 12:28
Contributor priority is set `Low` with reason: The issue is related to order of data restoring during application resumption.

**Comment by LitvinenkoIra** [comment] 2019-12-13 09:51
Defect is reproduced.
SDL branch: develop(e137556)
ATF: develop
Script: smartdevicelink/sdl_atf_test_scripts#2143

**Comment by LitvinenkoIra** [comment] 2019-12-13 10:15
#2515 - rebased to the latest develop
Fix is valid

**Comment by LitvinenkoIra** [comment] 2019-12-13 13:08
Full regression successfully passed
SDL: fix/sdl_must_restore_add_comm 4d4fd660
Scripts: develop 6f43bfd
ATF: develop 37da7aba

**Comment by LitvinenkoIra** [comment] 2019-12-13 13:08
@theresalech Please triage this issue

**Comment by theresalech** [comment] 2019-12-16 13:59
@LitvinenkoIra We are currently working on finalizing the roadmap with the Steering Committee, so will keep this issue in consideration for upcoming Core releases.

**Comment by iCollin** [comment] 2020-01-22 21:03
Closed via #2515

**Closed by iCollin** 2020-01-22 21:03 UTC
Labels: Bug, Sync4-CCB
