### ISSUE TITLE
SDL must start <DefaultTimeout>+<RPCs_own_timeout> for all RPCs with own timer

### ISSUE THREAD

**Issue by TMelnyk** [smartdevicelink/sdl_core#792] opened 2016-08-30 14:37 UTC
_Issue:_
Currently SDL starts **only** _"RPCs_internal_timer"_ for waiting the response from HMI for all RPCs with own timer.
This _"RPCs_internal_timer"_ is spent also for transferring request to HMI, reading RPC, etc.
As result, some delays was observed at response from HMI side.

_Solution:_
SDL must start **DefaultTimeout** _(from .ini file)_ **\+ RPCs_internal_timeout** for waiting the response from SDL side for **ALL** RPCs with own timer

**_List of impacted RPCs:_**
a. Alert _(“duration” param)_
b. PerformInteraction _(“timeout” param)_
c. Slider _(“timeout” param)_
d. ScrollableMessage _(“timeout” param)_

![applink_27301](https://cloud.githubusercontent.com/assets/17431970/18093403/5cce20d0-6ed8-11e6-9528-def8983b93f1.png)

**Comment by LitvinenkoIra** [comment] 2017-12-01 13:13
Priority Medium.
Loss of functionality on SDL side with standard use-case.

**Comment by LuxoftAKutsan** [comment] 2017-12-07 12:31
Looks like a duplicate of #1871

**Comment by jacobkeeler** [comment] 2018-03-08 18:54
Changing labels to match duplicate issue #1871

**Comment by GetmanetsIrina** [comment] 2018-05-03 12:35
Script for reproducing issue: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1880_DefaultAndRPCTimeoutGENERIC_ERROR.lua

**Comment by LitvinenkoIra** [comment] 2018-11-14 12:50
duplicate of https://github.com/smartdevicelink/sdl_core/issues/1880

**Comment by JackLivio** [comment] 2019-10-16 16:13
Fixed by #2495

**Closed by JackLivio** 2019-10-16 16:13 UTC
Labels: Bug, fix submitted
