### ISSUE TITLE
Using QT HMI

### ISSUE THREAD

**Issue by jiyouchen** [smartdevicelink/sdl_core#1673] opened 2017-07-20 08:39 UTC
I want to know how to compile with QT HMI.
Now when I set set(HMI_TYPE_OPTION 	"qt") in 'CMakeLists.txt',I got a error result:
[  9%] Built target intergen_utils
[ 34%] Built target intergen_model
[ 97%] Built target intergen_cppgen
[100%] Built target intergen
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/jiyou/sdl/build/tools/intergen/lib/libpugixml.so.1.2
-- Up-to-date: /home/jiyou/sdl/build/tools/intergen/lib/libpugixml.so
-- Up-to-date: /home/jiyou/sdl/build/tools/intergen/include/pugixml.hpp
-- Up-to-date: /home/jiyou/sdl/build/tools/intergen/include/pugiconfig.hpp
-- Up-to-date: /home/jiyou/sdl/build/tools/intergen/bin/intergen
[  7%] Completed 'intergen'
[  8%] Built target intergen
[  8%] Built target rpc_base
[  9%] Built target policy_struct
[  9%] Built target policyValidator
[  9%] Generating files:
   /home/jiyou/sdl/build/src/components/interfaces/QT_HMI_API.h;/home/jiyou/sdl/build/src/components/interfaces/QT_HMI_API_schema.h
   /home/jiyou/sdl/build/src/components/interfaces/QT_HMI_API_schema.cc
from:
   QT_HMI_API.xml ...

Generating interface source code with following parameters:
    Source xml      : /home/jiyou/sdl/sdl_core/src/components/interfaces/QT_HMI_API.xml
    Namespace       : hmi_apis
    Output directory: /home/jiyou/sdl/build/src/components/interfaces
    Parser type     : jsonrpc

Struct 'Common_DeviceInfo' is declared more than once

make[2]: *** [src/components/interfaces/QT_HMI_API.h] Error 22
make[1]: *** [src/components/interfaces/CMakeFiles/HMI_API.dir/all] Error 2

I don't how to fix this problem!

**Comment by jacobkeeler** [comment] 2017-10-19 19:28
Closing as duplicate of #1488

**Closed by jacobkeeler** 2017-10-19 19:28 UTC
