### ISSUE TITLE
Core sends an onAppInterfaceUnregistered notification when UnregisterAppInterface is sent from Mobile

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_core#1178] opened 2017-01-13 17:01 UTC
It seems as though we have an issue with core sending both an `onAppInterfaceUnregistered` notification and an `UnregisterAppInterface` response when the mobile proxy sends over `UnregisterAppInterface`. 
This should not be the case, as the notification should only be sent if there is an unregistration from the core side that was not caused by the mobile side. The notification also has a reason of -1, which is not a valid value. 

We should remove the notification from being sent when the `UnregisterAppInterface` RPC is sent.

**Comment by JackLivio** [comment] 2017-04-18 17:23
I will have to double check if that is expected behavior or if it is a bug. For now I am labeling as both a bug and a proposal

**Comment by LuxoftAKutsan** [comment] 2017-12-01 10:28
Priority is low
SDL send not critical additional notification

**Comment by jacobkeeler** [comment] 2018-03-08 21:51
Root cause: https://github.com/smartdevicelink/sdl_core/blob/master/src/components/application_manager/src/commands/mobile/unregister_app_interface_request.cc#L51

**Comment by joeljfischer** [comment] 2019-04-08 18:54
This has become a bigger issue with the iOS library recently due to Core sending the `-1` bad data. Ideally Core should never be sending data that doesn't match the type that's expected.

**Comment by HSavynetska** [comment] 2019-11-19 10:00
The defect is reproduced in the current develop branch

Environment:
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2109
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by E-SAITO-TMC** [comment] 2020-05-13 02:33
@theresalech -san, We were able to reproduce this issue with Core 6.0.1, This is a medium priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by iCollin** [comment] 2020-10-01 17:35
Closed via https://github.com/smartdevicelink/sdl_core/pull/3389

**Closed by iCollin** 2020-10-01 17:35 UTC
Labels: Bug, fix submitted, question
