### ISSUE TITLE
SDL sends not valid RegisterAppInterface response with not supported "name" in "textFields"

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1579] opened 2017-06-01 12:22 UTC
[SDL_log_646.txt](https://github.com/smartdevicelink/sdl_core/files/1044701/SDL_log_646.txt)
*Environment:*
OS: Ubuntu 16.04. 
ARC: PC (x86) 
SDL - Tag 4.2.1 commit e98cef965c4db1e3d9f1b225067571727ef1ecea
*Occurrence:*
Always
*Preconditions:*
SDL is running and HMI is connected to SDL
*Steps to reproduce:*
1) Register any application with SDL
2) Check RegisterAppInterface response

*Actual result:*
SDL respond with not not supported "name" : 28 param in "textFields"
*Expected result:*
SDL respond with valid RegisterAppInterface response
Requirements: MOBILE_API.xml

**Comment by jacobkeeler** [comment] 2018-03-08 20:40
Duplicate of #1392

**Closed by jacobkeeler** 2018-03-08 20:40 UTC
Labels: Bug
