### ISSUE TITLE
SDL crashes in case 'AppStorageFolder' doesn't have read/write permission

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2428] opened 2018-07-30 07:00 UTC
### Bug Report
SDL crashes in case 'AppStorageFolder' doesn't have read/write permission

##### Reproduction Steps
1. In case when there is no read/write permission
for the value of AppStorageFolder in smartDeviceLink.ini
the SDL crashes in initialization because the
assertion for the Protocol Handler instance fails.
The reason for this failure is that Protocol Handler
is not initialized due to failure of Application
Manager Init method caused by lack ot r/w permission.

##### Expected Behavior
SDL log an error and stop working correctly
There is no any dump

##### OS & Version Information
* OS/Version: 
* SDL Core Version:
* Testing Against:

**Comment by VjKlepikov** [comment] 2019-11-25 16:46
The issue is relevant on the current develop branch

Environment:
Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2097
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by iCollin** [comment] 2020-05-08 15:47
Closed via https://github.com/smartdevicelink/sdl_core/pull/2621

**Closed by iCollin** 2020-05-08 15:47 UTC
Labels: Bug
