### ISSUE TITLE
SDL does not validate invalid characters in HMI requests.

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#1862] opened 2017-11-20 11:44 UTC
### Bug Report
SDL does not validate invalid characters (\n, \t, only whitespace ) in string parameters in HMI requests.

##### Steps
1. HMI sends SDL.GetUserFriendlyMessage request with invalid characters

##### Expected Behavior
SDL responds with code INVALID_DATA to HMI.

##### Observed Behavior
SDL responds with code:0 (SUCCESS) to HMI.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 4eb09bf0da82e320723390abd877079af9457d20
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
* [Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1487432/Defects.zip)
* [SmartDeviceLinkCore.log.zip](https://github.com/smartdevicelink/sdl_core/files/1487434/SmartDeviceLinkCore.log.zip)

**Comment by aderiabin** [comment] 2017-12-01 12:43
Contributor priority is set `Medium` with reason: The issue is related to functionality: existence of response from HMI/SDL

**Comment by HSavynetska** [comment] 2018-06-23 12:22
Environment:
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1949
SDL build: develop branch (621080d)
ATF: develop branch

Status: defect is reproduced.

**Comment by ValeriiMalkov** [comment] 2018-07-31 09:46
The next PR provided fix this issue: [Pull request](https://github.com/smartdevicelink/sdl_core/pull/2390)

**Comment by VjKlepikov** [comment] 2019-11-25 08:58
The issue is relevant on the current develop branch

Environment:
Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1949
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by iCollin** [comment] 2020-05-20 20:09
Closed via https://github.com/smartdevicelink/sdl_core/pull/3369

**Closed by iCollin** 2020-05-20 20:09 UTC
Labels: Bug
