### ISSUE TITLE
Core prematurely sends success for DeleteInteractionChoiceSet

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_core#1833] opened 2017-10-31 18:05 UTC
### Bug Report
SDL Core deletes UI Interaction Choice set before response received from HMI for successfully deleting the corresponding VR Command. Core also responds success to mobile before knowing the status of the VR.DeleteCommand response. If the VR.DeleteCommand was unsuccessful then the mobile will no longer be synchronized with the state of the HMI.

##### Reproduction Steps
Change HMI to not respond to VR.DeleteCommand
Create Interaction choice set
Delete Interaction choice set

##### Expected Behavior
Mobile should receive error from core (Timed out or generic error)

##### Observed Behavior
Mobile receives success from core.

**Comment by aderiabin** [comment] 2017-12-01 12:52
Contributor priority is set `Medium` with reason: The issue is related to functionality: correctness of result code in response from HMI/SDL

**Comment by HSavynetska** [comment] 2019-11-21 08:56
The defect is reproduced on the current develop

Environment:
 Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2044
 SDL build: [https://github.com/smartdevicelink/sdl_core/tree/develop] (891497b )
 ATF: develop branch

**Comment by iCollin** [comment] 2021-05-04 18:37
Closed via https://github.com/smartdevicelink/sdl_core/pull/2601

**Closed by iCollin** 2021-05-04 18:37 UTC
Labels: Bug
