### ISSUE TITLE
SDL disallow Remote Control RPC call without commenting out DriverConsentCheck()

### ISSUE THREAD

**Issue by AKalinich-Luxoft** [smartdevicelink/sdl_core#2616] opened 2018-09-17 15:43 UTC
**Preconditions:**
 1. RC App is registered and active on HMI
 2. RC App ID has RC related RPCs in list of allowed RPCs to be processed in FULL

**Steps:**
 1. Send GetInteriorVehicleData with valid params.

**Expected Result:**
SDL process request to AppLink
 
**Actual Result:**
SDL disallow RPC (only with temp solution of comment out DriverConsentCheck()

**Comment by ShobhitAd** [comment] 2020-05-18 14:08
Unable to reproduce issue using the latest develop(https://github.com/smartdevicelink/sdl_core/commit/86f87ca36c83f552d414033d0c3c2a7a818b733d). The issue seems to have been resolved by the  merge of https://github.com/smartdevicelink/sdl_core/pull/2676

**Closed by ShobhitAd** 2020-05-18 14:08 UTC
Labels: Bug
