### ISSUE TITLE
Processing invalid PT after cutting off unknown_parameter or unknown_RPC

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#1921] opened 2017-11-24 10:47 UTC
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register new application
5. Create PT for policy table update with unknown_parameter or unknown_RPC
6. Perform policy table update from mobile app with created PT

## Expected result
1. SDL received UpdatedPT with at least one <unknown_parameter> or <unknown_RPC>
and after cutting off <unknown_parameter> or <unknown_RPC> UpdatedPT performs validation of received PT
2. SDL must log the error internally and discard Policy Table Update

## Actual result
SDL performs PT validation without cutting off <unknown_parameter> or <unknown_RPC>

## Test script
[1921_Invalid_PT_after_cutting_unknow_values.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua)

## Attachments

# Expected delivery
- [x] Source code updates
- [x] Code comments
- [x] **UTs add/update _(not required)_**
- [x] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by dboltovskyi** [comment] 2017-12-01 12:16
Priority was set to High. Updating policy with invalid PTU (which contains unknown RPC or parameter) may affect application permissions calculating process.

**Comment by GetmanetsIrina** [comment] 2017-12-27 11:58
Issue is reproduced on develop branch 61c37f3763b7f84dca8f42ffdaa705d454d1b711.

**Comment by LuxoftAKutsan** [comment] 2017-12-27 14:24
Issue is related to https://github.com/smartdevicelink/sdl_core/issues/1885

**Comment by LuxoftAKutsan** [comment] 2017-12-27 14:31
Fix is available https://github.com/smartdevicelink/sdl_core/pull/1972 

But fix is partial. It includes only cutting off <unknown_parameter>  And It does not cut's of  <unknown_RPC>. 

This is done because functionality of cutting of <unknown_RPC> is also absent in Sync 3.2v2 repo. To make code aligned it was not implemented in opensdl.

Missing functionality of cutting <unknown_RPC> is not critical and does not breaks any use cases. 
In case of Mobile application will send RPC with unknown FunctionID, it will be rejected during parsing, and policy login won't be involved. Locating of <unknown_RPC> in PolicyTable does not affect other RPCs in any use cases. 

Implementation of of cutting <unknown_RPC> is possible, but it should be done both in openSDL and in Sync3.2v2. Also this regression of this implementation might be rather big. 

@robinmk  please considering this points, should cutting <unknown_RPC> functionality be implemented or not?

**Comment by robinmk** [comment] 2017-12-28 23:56
@LuxoftAKutsan , I have the same understanding as well - that unknown RPCs will be rejected/ignored early on and hence it would not break policies. If there is any change in this understanding please inform us as we will need to address at the earliest.
Let's also wait for @mrapitis  to comment.

**Comment by mrapitis** [comment] 2018-01-02 14:34
@LuxoftAKutsan I agree with @robinmk comment as well -- the RPC should send a generic response back to the mobile if it is of an unknown type (as it does today) which should not impact policies.

**Comment by LuxoftAKutsan** [comment] 2018-02-05 15:48
@robinmk @mrapitis good, so please approve that cutting <unknown_RPC> functionality should not be implemented.

**Comment by mrapitis** [comment] 2018-05-25 15:32
@GetmanetsIrina are there any remaining tasks required here?  It looks like we still have three items unchecked in the expected delivery section.  Can you please check them if this was an oversight?

**Comment by GetmanetsIrina** [comment] 2018-05-29 09:03
@mrapitis , task status is updated, thanks! https://github.com/smartdevicelink/sdl_core/pull/1972 is mentioned above.

**Comment by LuxoftAKutsan** [comment] 2018-05-29 13:35
@mrapitis Sorry, the #2006 is the correct PR.

**Comment by mrapitis** [comment] 2018-05-29 14:07
@LuxoftAKutsan how to #2006 and #1972 differ? it looks like #1972 was already reviewed?

**Comment by LuxoftAKutsan** [comment] 2018-05-29 15:26
@mrapitis #2006 also reviewed, but not by zhimin.
I would say that #1972 is not ready and looks like a draft version. #2006 is the same approach but is more clear and finished. It is my fail that there was 2 PRs, #1972 should be closed. I will close it if you don't mind

**Closed** 2018-09-21 14:11 UTC
Labels: Bug, Contributor priority 1: High, fix submitted
