### ISSUE TITLE
SmartDeviceLink crashes on boot.

### ISSUE THREAD

**Issue by IGapchuk** [smartdevicelink/sdl_core#2569] opened 2018-09-05 13:06 UTC
### Bug Report
SmartDeviceLink crashes on boot.

##### Reproduction Steps
1. Simulate ignition OFF.
(Send from HMI send notification OnExitAllApplications(IGNITION_OFF))
2. Wait 2 minutes.
3. Simulate ignition ON. (start SDL)
4. Wait between 1 and 16 seconds (varying in each iteration).
5. Simulate gear change to R
(Send from HMI send request "VehicleInfo" {prndl="REVERSE"})
6. Wait between 6 and 12 seconds (varying in each iteration).
7. Simulate gear change to D
(Send from HMI send request "VehicleInfo" {prndl="DRIVE"})
8. After 10 seconds, simulate gear change to P.
(Send from HMI send request "VehicleInfo" {prndl="PARK"})
9. Wait 2 minutes.
Repeat 1 - 9 for several times.

##### Expected Behavior
No catastrophic failures. All functionality verified.

##### Observed Behavior
SmartDeviceLink crashes on boot.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: develop

**Comment by jacobkeeler** [comment] 2021-04-14 20:13
Looks to be a duplicate of https://github.com/smartdevicelink/sdl_core/issues/3163, which is already fixed. Closing for now, please reopen if this issue is still relevant.

**Closed by jacobkeeler** 2021-04-14 20:13 UTC
Labels: Bug, fix submitted
