### ISSUE TITLE
SDL sends SubscribeVehicleData by resumption second app

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#2283] opened 2018-06-20 08:22 UTC
### Bug Report
SDL sends SubscribeVehicleData by registration second app

##### Reproduction Steps
1. Register app1 and app2
2. App1 subscribe VD and App2 subscribe the same VD
3. Reconnect apps

##### Expected Behavior
1. SDL resumes SubscribeVehicleData for app1 and sends SubscribeVehicleData request to HMI
2. SDL resumes SubscribeVehicleData for app2 and does not send SubscribeVehicleData request to HMI

##### Observed Behavior
SDL sends SubscribeVehicleData requests to HMI during resumption of both apps.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: develop branch (2ec732c56e3f06b7043cf02cf98109720d6ff38a)
* Testing Against: ATF: [develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1936 (004_Resumption_success_flow_2_apps.lua)

##### Attach
[SmartDeviceLinkCore_subscribeVD_resumption_2app.log.tar.gz](https://github.com/smartdevicelink/sdl_core/files/2118442/SmartDeviceLinkCore_subscribeVD_resumption_2app.log.tar.gz)

**Comment by HSavynetska** [comment] 2019-11-25 15:57
The issue is relevant on the current develop branch

Environment:
Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1936
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by jacobkeeler** [comment] 2020-06-25 14:57
Closing with the merge of #3355

**Closed by jacobkeeler** 2020-06-25 14:57 UTC
Labels: Bug
