### ISSUE TITLE
PolicyTableUpdate is failed by any reason and "ForceProtectedService"=OFF at .ini file

### ISSUE THREAD

**Issue by AStasiuk** [smartdevicelink/sdl_core#1891] opened 2017-11-23 15:33 UTC
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Set ForceProtectedService = Non in smartDeviceLink.ini
3. Start SDL and HMI
4. Connect mobile device
5. Register navi mobile application
6. PTU is triggered and failed because of invalid PT( In script missed seconds_between_retries in PT )
7. Activate App
8. Start secure audio/video/RPC service

## Expected result
1. For audio/video services: SDL responds StartServiceACK(encrypted=false) to this mobile application and starts not secure service.
2. For RPC service: SDL responds StartServiceNACK since unprotected RPC service is started already.

## Actual result
1. SDL works as expected.
2. SDL responds StartServiceACK (encrypted=false).

## Test scripts
[1891_1_navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1891_1_navi.lua)
[1891_2_non-navi.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1891_2_non-navi.lua)
[1891_3_navi_audio.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1891_3_navi_audio.lua)
[1891_4_navi_video.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1891_4_navi_video.lua)

## Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment] 2017-12-01 12:14
Contributor priority is set High with reason: The issue is related to secure service start logic.

**Comment by dboltovskyi** [comment] 2017-12-27 12:57
Issue is reproduced on develop branch (0b19cf4)

**Comment by jacobkeeler** [comment] 2018-01-31 18:26
Verified that this is fixed by #1971.

**Comment by jacobkeeler** [comment] 2018-01-31 21:10
Fixed with the merge of #1971

**Closed by jacobkeeler** 2018-01-31 21:10 UTC
Labels: Bug, Contributor priority 1: High
