### ISSUE TITLE
SDL must set media app to FULL and NOT_AUDIBLE in case this app is activated during phone call

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2323] opened 2018-07-03 13:31 UTC
### Bug Report
SDL must set media app to FULL and NOT_AUDIBLE in case this app is activated during phone call

##### Reproduction Steps
1. SDL and HMI are started.
2. Media app is registered
3. HMI sends `OnEventChanged(PHONE_CALL, isActive=true)`
3. SDL receives `SDL.ActivateApp(<appID_of_media_app>)` request from HMI during phone call

##### Expected Behavior
1. SDL must respond `SDL.ActivateApp (SUCCESS)` to HMI
2. SDL sends `OnHMIStatus(FULL, NOT_AUDIBLE)` to mobile app
3. After the phone call ends and SDL receives `OnEventChanged(PHONE_CALL, isActive=false)` from HMI, SDL must send `OnHMIStatus(FULL, AUDIBLE)` to mobile app

##### Observed Behavior
1. SDL sends `OnHMIStatus(BACKGROUND, NOT_AUDIBLE)` to mobile app during activation
2. SDL does not send `OnHMIStatus(FULL, AUDIBLE)` to mobile app after the phone call ends and SDL receives `OnEventChanged(PHONE_CALL, isActive=false)` from HMI.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: develop branch (ba1da7b)
* Testing Against: ATF: [develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1956

##### Attach
[TestingReports.zip](https://github.com/smartdevicelink/sdl_core/files/2159501/TestingReports.zip)

**Comment by HSavynetska** [comment] 2018-07-09 13:12
Environment:
Script: smartdevicelink/sdl_atf_test_scripts#1956
SDL build: develop branch (ba1da7b)
ATF: develop branch

Status: defect is reproduced.

**Comment by VjKlepikov** [comment] 2019-11-22 16:03
The issue is relevant on the current develop branch

Environment:
Test script: smartdevicelink/sdl_atf_test_scripts#1956
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by dboltovskyi** [comment] 2020-06-15 15:59
Please notice issue is still actual for Core 6.1
ATF script and logs: [2020-06-15_11-58-52_2323.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4781459/2020-06-15_11-58-52_2323.tar.gz)

**Comment by jacobkeeler** [comment] 2021-08-18 21:27
Closed via #3738

**Closed by jacobkeeler** 2021-08-18 21:27 UTC
Labels: Bug
