### ISSUE TITLE
SDL must set media app to LIMITED and AUDIBLE due to active embedded navigation

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2322] opened 2018-07-03 12:41 UTC
### Bug Report
SDL must set media app to LIMITED and AUDIBLE due to active embedded navigation

##### Reproduction Steps
1. SDL and HMI are started.
2. Media app is registered and activated`(FULL, AUDIBLE)`.
3. SDL receives `OnEventChanged(EMBEDDED_NAVI, isActive=true)` from HMI.

##### Expected Behavior
SDL must send `OnHMIStatus(LIMITED, AUDIBLE)` to mobile app.

##### Observed Behavior
SDL sends `OnHMIStatus(BACKGROUND, NOT_AUDIBLE)` to mobile app.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: develop branch (ba1da7b)
* Testing Against: ATF: [develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1957

##### Attach
[TestingReports.zip](https://github.com/smartdevicelink/sdl_core/files/2159294/TestingReports.zip)

**Comment by HSavynetska** [comment] 2018-07-04 13:47
Environment:
Script: smartdevicelink/sdl_atf_test_scripts#1957
SDL build: develop branch (ba1da7b)
ATF: develop branch

Status: defect is reproduced.

**Comment by VjKlepikov** [comment] 2019-11-22 15:51
The issue is relevant on the current develop branch

Environment:
Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1957
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop ( 891497b )
ATF: develop branch

**Comment by E-SAITO-TMC** [comment] 2020-05-13 02:13
@theresalech -san, We were able to reproduce this issue with Core 6.0.1. This is a high priority issue for Toyota. Could you please include this in the Core 6.2 release planning?

**Comment by theresalech** [comment] 2020-05-21 13:04
@HSavynetska can you please advise if you are able to reproduce this issue in the latest Core release?

**Comment by dboltovskyi** [comment] 2020-06-04 19:27
@theresalech Please notice issue is still actual for Core 6.1
ATF script and logs: [2020-06-04_15-26-34_2322.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4732309/2020-06-04_15-26-34_2322.tar.gz)

**Comment by theresalech** [comment] 2020-06-08 15:09
@dboltovskyi thank you for the update!  Can you please advise if Luxoft is planning to submit a PR to resolve this issue?

**Comment by dboltovskyi** [comment] 2020-06-11 17:34
@theresalech Please notice we're not planning to create the fix in scope of 6.2.

**Comment by iCollin** [comment] 2020-07-20 19:31
It seems that there are two ATF tests expecting the incorrect behavior:
`./test_scripts/MobileProjection/Phase2/003_audioStreamingState_069-103.lua`
`./test_scripts/MobileProjection/Phase2/020_different_types_apps_interactions.lua`

Would it be possible to update the expectations in [ATF PR 1957](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1957)?

**Comment by jacobkeeler** [comment] 2020-09-04 15:23
Closing with the merge of #3476

**Closed by jacobkeeler** 2020-09-04 15:23 UTC
Labels: Bug
