### ISSUE TITLE
SDL Send GENERIC_ERROR result code to MOBILE instead of SUCCESS in ScrollableMessage

### ISSUE THREAD

**Issue by dsmyrnov** [smartdevicelink/sdl_core#1695] opened 2017-07-28 11:12 UTC
Environment:
OS: Ubuntu 16.04.
ARC: PC (x86)
SDL - Tag 4.2.1 commit e98cef9
Occurrence:
Always
Preconditions:
SDL is running and HMI is connected to SDL
Application registered
Steps to reproduce:
Send  ScrollableMessage, wait nearly 30 sec (till HMI respond with SUCCESS)
Actual result:
SDL sends to application GENERIC_ERROR
[SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/1182820/SmartDeviceLinkCore.txt)

Expected result:
SDL sends to application SUCCESS
Requirements: MOBILE_API.xml

**Comment by jacobkeeler** [comment] 2018-03-07 22:29
Duplicate of #792

**Closed by jacobkeeler** 2018-03-07 22:29 UTC
