### ISSUE TITLE
[Help] SDL Core Internal Error callback func?

### ISSUE THREAD

**Issue by yifili09** [smartdevicelink/sdl_core#32] opened 2015-02-09 08:42 UTC
Hi, Guys.

The response of "RegisterAppInterface" shall indicate whether the app could be list on the Head Unit.

Are there any internal Error callbacks / Notifications from SDL Core to Head Unit such as 
- JSON parsing(Proxy) errors
- App crash erros
- JSON request/response generating erros
- Transiting data corruption
etc

Thanks a lot!

**Comment by justinjdickow** [comment] 2015-02-09 15:34
@yifili09 Could you clarify what you mean by SDL Core to the Head Unit? Also, do you think this issue is a duplicate of #31?

**Comment by yifili09** [comment] 2015-02-10 01:58
Head Unit could be referred to HMI. 
There should be possibility that HMI can not start the application. 

Is there any pre-defined func by SDL Core to meet with the scenario? Thanks.
![can_not_start_app](https://cloud.githubusercontent.com/assets/1016943/6119904/207e4af2-b10a-11e4-826f-3385c8ebb08c.png)

**Comment by justinjdickow** [comment] 2015-02-10 03:29
In the current API version no, but in 4.0 we're adding an error and error code to SDL.ActivateApp. When the application is listed but cannot be launched, the error code will return "APPLICATION_NOT_REGISTERED".

The reason this API does not exist in the current version is that an application cannot be listed by SDL unless it is launched on the phone, has been connected, and is already registered with the head unit and at least placed in the HMI_NONE or HMI_LIMITED state. When applications are disconnected or unregistered in the current version they are removed from the list. In 4.0, applications which can be remotely launched and connected will be in the list even if they aren't currently registered.

**Closed** 2015-02-10 03:30 UTC

**Comment by justinjdickow** [comment] 2015-02-11 12:56
@yifili09 Here is more accurate technical information regarding this question

>   1.1. requested app is successfully launched:
        HMI->SDL: SDL.ActivateApp_request (app_1) 
        SDL->app_launcher: OnSystemRequest(launch_app)
        app_1->SDL: RegisterAppInterface 
        SDL->HMI: OnAppRegistered (app_1) 
        SDL->HMI: SDL.ActivateApp_response (app_1)
    In order not to make changes to SDL.ActivateApp, it was decided to reuse OnAppRegistered for providing HMI with registration-related details.

   >1.2. requested app was not launched (=not registered during SDL's timeout started after sending OnSystemRequest(launch_app) to mobile):
        HMI->SDL: SDL.ActivateApp_request (app_1) 
        SDL->app_launcher: OnSystemRequest(launch_app)
        app_1 does not register during timeout
        SDL->HMI: SDL.ActivateApp_error (result: APPLICATION_NOT_REGISTERED)
