### ISSUE TITLE
CCB : Smartdevicelink crash observed when 2 Nav apps are connected to SYNC and multiple RPC are sent

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_core#3412] opened 2020-05-29 11:35 UTC
### Bug Report

Crash occurs in SYNC and the system reboots.
Smartdevicelink crash is generated

##### Reproduction Steps
Pre-Requisite:
1. Turn IGN to Run
2. Android device is connected to SYNC via BT
3. iPhone is connected to the SYNC via USB.
4. Make sure Antelope App is uninstalled in iPhone.
5. In Android, in SyncProxyTester app, create a proxy "Navigation" (App ID: 883259982, Media Unchecked, HMI type: Navigation)
6. In iPhone device, configure SPT3 app as "Antelope" (App ID: 2160742002, Media Unchecked, HMI type: Navigation)
7. Make sure both the apps are launched in phone and registered in SYNC.
8. Disable encryption in smartdevicelink.ini file in the file system

Reproduction steps:
1. Select Apps from Status/Interaction bar and select Navigation app and start A/V streaming.
2. Select Apps from Status/Interaction bar and select Antelope app and start A/V streaming.
3. Send multiple Alert RPCs from both devices.
4. Observe the HMI behavior and mobile notifications.

##### Expected Behavior
 SYNC should execute all the RPCs without any crash.

##### Observed Behavior
Crash occurs in SYNC and the system reboots.
Smartdevicelink crash is generated

Occurrence: 1/10

##### OS & Version Information

    OS/Version: QNX 7.0
    SDL Core Version: 5.0.1 integrated to SYNC environment
    Testing Against: 
Device used: Google Galaxy Pixel 3XL, iPhone X
Device Version: 9
SPT version: 4.6.2
App Name: SyncProxyTester
App Id: 584421907

**Comment by ychernysheva** [comment] 2020-11-24 12:18
Root cause of this issue is incorrect behavior of logger during deleting of corresponding plugin, because previously each plugin had its own instance of logger. But now this issue is not relevant due to feature [Implement logger abstraction](https://github.com/smartdevicelink/sdl_core/issues/1480), where this problem was solved as a part of feature implementation. Now `Logger` is a singleton class, which is passed by pointer to each plugin during creation so that plugins can initialize the `Logger::instance` pointer with the instance received from SDL core. So now we don't need to care about deleting of several logger instances.

Also note that all lifecycle of concrete logger now is controlled by `LoggerImpl` class, so all functional, related to logger deinitialization, is already incapsulated inside of this class.

That's why this issue is outdated and may be closed as not actual.

**Closed by ychernysheva** 2020-11-24 12:18 UTC
