### ISSUE TITLE
SDL core dump is observed when send SDL_STOP message to mqueue (iAP)

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2466] opened 2018-07-30 13:43 UTC
### Bug Report
SDL core dump is observed when send SDL_STOP message to mqueue (iAP)

#### Preconditions:

1. First SDL life cycle.
2. HMI, is started.

##### Reproduction Steps
1. Connect mobile to HU.
2. Applications are registered.
3. Send SDL_STOP message to mqueue (In terminal execute:
echo '\0021' > /dev/mqueue/AppLinkSDLProxy)
4. Power on/off HU.

##### Expected Behavior
No SDL core dumps.

##### Observed Behavior
SDL core dump is observed in /fs/rwdata/dumps

##### OS & Version Information
* OS/Version: 
* SDL Core Version:
* Testing Against:

**Comment by LitvinenkoIra** [comment] 2018-09-03 14:53
duplicate of https://github.com/SmartDeviceLink/sdl_core/issues/2434

**Closed by LitvinenkoIra** 2018-09-03 14:53 UTC
Labels: Bug, Contributor priority 1: High
