### ISSUE TITLE
SDL must start PTU for navi app right after app successfully registration

### ISSUE THREAD

**Issue by AStasiuk** [smartdevicelink/sdl_core#1925] opened 2017-11-24 14:00 UTC
**Occurrence: Always** 

## Steps to reproduce
1. Make sure SDL is built with default flags
2. Start SDL and HMI
3. Connect mobile device
4. Register non-navi mobile application
5. PTU for registered application without certificate and with navi application in PT is performed
6. Register navi application

## Expected result
SDL starts PolicyTableUpdate process on sending SDL.OnStatusUpdate(UPDATE_NEEDED) to HMI to get "certificate" after app successfully registration.

## Actual result
SDL does not start PolicyTableUpdate process.

## Test scripts
[1925_1_navi_no_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_1_navi_no_cert_new_app.lua)
[1925_2_navi_no_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_2_navi_no_cert_existing_app.lua)
[1925_3_navi_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_3_navi_cert_new_app.lua)
[1925_4_navi_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_4_navi_cert_existing_app.lua)
[1925_5_non-navi_no_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_5_non-navi_no_cert_new_app.lua)
[1925_6_non-navi_no_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_6_non-navi_no_cert_existing_app.lua)
[1925_7_non-navi_cert_new_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_7_non-navi_cert_new_app.lua)
[1925_8_non-navi_cert_existing_app.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/1925_8_non-navi_cert_existing_app.lua)

## Attachments

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by dboltovskyi** [comment] 2017-12-01 12:15
Priority was set to High. Issue makes impossible starting of secure sessions because of absent certificate in PT. TLS handshake will not be resumed until valid certificate will be received.

**Comment by dboltovskyi** [comment] 2017-12-27 12:57
Issue is reproduced on develop branch (0b19cf4)

**Comment by jacobkeeler** [comment] 2018-01-31 21:10
Fixed on current develop branch

**Closed by jacobkeeler** 2018-01-31 21:10 UTC
Labels: Bug, Contributor priority 1: High
