### ISSUE TITLE
SDL must close only session in case mobile app does not answer on Heartbeat_request

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#1893] opened 2017-11-23 15:56 UTC
## Occurrence: 
Always 

## Steps to reproduce:
1. Reduce default value for Heartbeat timeout in SDL .INI file to 5 sec.
2. Start SDL
3. Start HMI
4. Connect mobile device
5. Register mobile application (sending of Heartbeat from application is switched off)
6. Wait 15 seconds
7. Check that app is unregistered
8. Check that mobile connection is still alive

## Expected result:
Mobile connection is still alive and it's possible to create new mobile session

## Actual result:
Mobile connection is closed

## Test script:
[1893_ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1893_ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [x] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment] 2017-12-01 12:11
Contributor priority is set `High` with reason: The issue is related to connection/session logic
Mobile applications should work independently one from other.

**Comment by LitvinenkoIra** [comment] 2017-12-04 14:33
Works correctly on current develop (8c94933)
Script for verifying and testing report [1893.tar.gz](https://github.com/smartdevicelink/sdl_core/files/1527442/1893.tar.gz)

**Comment by LuxoftAKutsan** [comment] 2017-12-11 08:50
@jacobkeeler @JackLivio please close the issue.

**Comment by LuxoftAKutsan** [comment] 2017-12-14 14:01
HeartBeatMonitor is in charge of monitoring heartbeat timeout. There is separate  HeartBeatMonitor for each connection.
It has separate own thread that executing `HeartBeatMonitor::Process` function. 
HeartBeatMonitor handles session numbers and monitors heartbeat for each session : 
```
class HeartBeatMonitor : public threads::ThreadDelegate {
...
   * \brief add and remove session
   */
  void AddSession(uint8_t session_id);
  void RemoveSession(uint8_t session_id);
...
```
```
void HeartBeatMonitor::Process() {
  sessions_list_lock_.Acquire();
  SessionMap::iterator it = sessions_.begin();
  while (it != sessions_.end()) {
  ...
```
And in case if Hearbeat timeout elapsed HeartBeatMonitor will close certain session  : 
```cpp
void HeartBeatMonitor::Process() {
...
    if (state.HasTimeoutElapsed()) {
      const uint8_t session_id = it->first;
      if (state.IsReadyToClose()) {
        LOG4CXX_WARN(logger_, "Will close session");
        sessions_list_lock_.Release();
        RemoveSession(session_id);
        connection_->CloseSession(session_id);
        sessions_list_lock_.Acquire();
...
}
```

**Comment by dboltovskyi** [comment] 2017-12-20 10:49
There is some extension for the initial requirement:
SDL should not close mobile connection even if last session on this connection had been closed.

Currently on a head of develop SDL close such connection, so issue is reproduced.

Description of the issue is updated.
Test script is also updated accordingly.

**Comment by mrapitis** [comment] 2017-12-21 21:21
Requires additional testing with the updated script that is provided.

**Comment by GetmanetsIrina** [comment] 2017-12-22 08:24
Defect is reproduced on develop branch(0b19cf498d1c9972d67b85793dc6b029c26378a0).
Fix in https://github.com/smartdevicelink/sdl_core/pull/1965(0abb3c77bd9fad9a8070e4a9b041536c4356af5f),
ATF version for verification https://github.com/smartdevicelink/sdl_atf/commits/develop(ae3c97da2ca77031b645773917b63eff1421c04d) with HB fix,
script for verification https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1893_ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua.

**Closed** 2018-09-04 18:11 UTC
Labels: Bug, Contributor priority 1: High, fix submitted
