### ISSUE TITLE
SDL does not send default vrHelp to HMI if App was registered with vrSynonyms

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#999] opened 2016-11-07 17:27 UTC
## Occurrence
Always.

## Preconditions
1. Core, HMI started.
2. App is registered on HMI.
3. App provided vrSynonyms in RegisterAppInterface.

## Steps to reproduce
1. Send SetGlobalProperties with only "menuTitle" parameter

## Expected result
SDL should send default vrHelp and vrHelpTitle

## Actual result
SDL do not send vrHelp at all.

**Note:** Problem can be reproduced with attached ATF script.

# Environment
SDL branch: master
SDL commit: a6c32b4
HMI: HTML5
OS: Ubuntu 14.04 LTS
Transport: WiFi
Mobile device: HTC One
Mobile OS: Android 4.3
Mobile App version: SPT v.2.1.81 Code: 239
Mobile App type (media/non-media/navi/any): any

# Attachments
[att_issue#999.zip](https://github.com/smartdevicelink/sdl_core/files/576127/att_issue.999.zip)

# Expected delivery   
- [ ] Source code updates 
- [ ] Code comments 
- [ ] UTs add/update 
- [x] ATF tests add/update ***(not required)***  
- [x] Manual tests ***(not required)*** 
- [x] Add/update CI plans/jobs ***(not required)***  
- [x] SDD updates ***(not required)***  
- [x] Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) ***(not required)***  
- [x] Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines))  ***(not required)***

**Comment by LitvinenkoIra** [comment] 2017-12-01 12:41
Priority Medium.
Loss of functionality on SDL side with standard use-case.

**Comment by jacobkeeler** [comment] 2018-03-08 21:30
Duplicate of #1306

**Closed by jacobkeeler** 2018-03-08 21:30 UTC
Labels: Bug, Contributor priority 2: Medium
