### ISSUE TITLE
Policy Table fails to load if SDL encounters an unknown parameter

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_core#1514] opened 2017-04-27 17:33 UTC
Currently SDL's policy table validation routine has an error that prevents it from loading a policy table with new parameters inside of a functional group. If SDL attempts to load a policy table that contains parameters that it is unaware of, the policy table will fail to load and SDL will log an error. In other words, adding a new parameter to an existing RPC will break policy table processing.

To Reproduce: 
Add a new parameter to an existing rpc and its associated functional group in the sdl preload table. Overwrite the default preload table with the modified version containing your changes.   Perform a fresh Startup sdl core and make sure that logs are on.  Take note of the entry below (or similar based on the functional group that was updated) in the SmartDeviceLinkCore.log.  Policy table processing is then halted.  

Expected Behavior:
Instead of halting processing all together when an unknown parameter is encountered, sdl core should ignore unknown parameters and continue processing the functional grouping -- this ensures backwards compatibility as new parameters are added to groupings in the future.

To quickly repro the issue, I have attached a sample sdl_preloaded_pt.json file with a new parameter of testparam in the DrivingCharacteristics-3 functional group.  I have also included the logs and sqlite policy table generated by sdlcore when processing the preload.

``
:LoadFromFile: Parsed table is not valid policy_table.policy_table.functional_groupings["DrivingCharacteristics-3"].rpcs["GetVehicleData"].parameters[6]: value initialized incorrectly
``
[policy-issue.zip](https://github.com/smartdevicelink/sdl_core/files/962379/policy-issue.zip)

**Comment by jacobkeeler** [comment] 2019-04-08 20:14
Duplicate of https://github.com/smartdevicelink/sdl_core/issues/1921

**Closed by jacobkeeler** 2019-04-08 20:14 UTC
Labels: Bug, best practice
