### ISSUE TITLE
SDL doesn't provide individual VD result code for clusterModeStatus in SubscribeVehicleData/UnsunscribeVehicleData responses from HMI

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_core#3460] opened 2020-07-15 17:40 UTC
### Bug Report
SDL doesn't provide individual VD result code for `clusterModeStatus` in `SubscribeVehicleData/UnsunscribeVehicleData` responses from HMI in case of 2 apps.

##### Reproduction Steps
*Preconditions:*
1. SDL and HMI are started
2. `SubscribeVehicleData` RPC and `<vd_param>` parameter are allowed by policies
3. `App_1` and `App_2` are registered
4. `App_1` successfully subscribes to `<vd_param>`

*In case:*
1. `App_2` sends valid `SubscribeVehicleData(<vd_param>=true)` request to SDL

##### Expected Behavior
SDL does:
- send SubscribeVehicleData response with `(success = true, resultCode = "SUCCESS",
 <vd_param> = <data received from HMI>)` to `App_2`
- not transfer this request to HMI

##### Observed Behavior
SDL does:
- not send `<vd_param> = <data received from HMI>)` in response to `App_2`

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (81fb32e)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF and SDL logs: [2020-07-15_13-31-09_3460.tar.gz](https://github.com/smartdevicelink/sdl_core/files/4926965/2020-07-15_13-31-09_3460.tar.gz)

**Comment by dboltovskyi** [comment] 2020-07-15 17:43
Please take into account that for `SubscribeVehicleData/UnsunscribeVehicleData` real VD parameter name is `clusterModes` instead of `clusterModeStatus`
This discrepancy was described in issue https://github.com/smartdevicelink/sdl_core/issues/1696

**Comment by theresalech** [comment] 2021-11-10 18:32
@dboltovskyi can you please advise if Luxoft is planning to submit a PR to resolve this issue? Thank you!

**Comment by dboltovskyi** [comment] 2021-11-10 20:50
@theresalech Yes, Luxoft team is planning to submit a fix for this issue.

**Comment by ShobhitAd** [comment] 2022-01-07 22:10
Closed via https://github.com/smartdevicelink/sdl_core/pull/3830

**Comment by VjKlepikov** [comment] 2022-01-19 11:40
The issue is reproduced on the current develop branch [8f1ccb2](https://github.com/smartdevicelink/sdl_core/tree/develop) for new scripts PR [2618](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2618)
Logs: [2022-01-17_08-33-54.236_failed.tar.gz](https://github.com/smartdevicelink/sdl_core/files/7896734/2022-01-17_08-33-54.236_failed.tar.gz)

**Comment by jacobkeeler** [comment] 2022-01-19 19:15
@VjKlepikov It looks like the failure in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2618 is slightly different than the described issue, but similar. In this case, if the app requests `clusterModeStatus` in `SubscribeVehicleData` (along with other parameters) when it does not have permissions for `clusterModeStatus`. Core should send `clusterModes` in the response with the `DISALLOWED` result code, but instead it omits the `clusterModes` parameter.

**Comment by ShobhitAd** [comment] 2022-02-01 14:29
Closed via https://github.com/smartdevicelink/sdl_core/pull/3847

**Closed by ShobhitAd** 2022-02-01 14:29 UTC
Labels: Bug
