### ISSUE TITLE
CCB: Processing invalid RPCs 

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#1865] opened 2017-11-21 08:46 UTC
### Bug Report
SDL does not handle correctly invalid messages from HMI

##### Reproduction Steps
1. HMI sends any of the invalid message from the list below to SDL:
a) array size of parameter is beyond the max restriction
b) string value of parameter is beyond the max restriction
c) invalid value type of parameter
d) missing mandatory parameter
e) empty string value for parameter

##### Expected Behavior
1. SDL responds with code INVALID_DATA to HMI
2. Log internal error 

##### Observed Behavior
1. SDL does not send response to HMI
2. Doesn't log error

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/tree/develop)
* Testing Against: ATF

**Comment by LuxoftAKutsan** [comment] 2017-11-21 12:32
@GetmanetsIrina  please all links to #1869 #1868 #1867 #1866 they probably have same root cause

**Comment by aderiabin** [comment] 2017-12-01 12:42
Contributor priority is set `Medium` with reason: The issue is related to functionality: existence of response from HMI/SDL

**Comment by HSavynetska** [comment] 2018-07-05 13:54
Environment:
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1962
SDL build: develop branch ( ba1da7b )
ATF: develop branch

Status: Defect is reproduced.

**Comment by ValeriiMalkov** [comment] 2018-07-31 09:48
The next PR provided fix this issue: [Pull request](https://github.com/smartdevicelink/sdl_core/pull/2394)

**Comment by LitvinenkoIra** [comment] 2019-12-12 13:33
Defect is reproduced.
SDL branch: develop(e137556)
ATF: develop
Script: smartdevicelink/sdl_atf_test_scripts#1962

**Comment by LitvinenkoIra** [comment] 2019-12-12 13:49
#2394 - rebased to the latest develop
Fix is valid

**Comment by LitvinenkoIra** [comment] 2019-12-13 09:30
Full regression successfully passed
SDL: fix/request_from_hmi_has_para bbd14149
Scripts: develop 6f43bfd
ATF: develop 37da7aba

**Comment by LitvinenkoIra** [comment] 2019-12-13 09:31
@theresalech Please triage this issue

**Comment by theresalech** [comment] 2019-12-16 13:59
@LitvinenkoIra We are currently working on finalizing the roadmap with the Steering Committee, so will keep this issue in consideration for upcoming Core releases.

**Comment by iCollin** [comment] 2020-01-21 21:26
Closed via #2394

**Closed by iCollin** 2020-01-21 21:26 UTC
Labels: Bug, Sync4-CCB
