### ISSUE TITLE
CCB: Update verification criterias for malformed messages 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2384] opened 2018-07-18 11:52 UTC
### Bug Report
SDL should mark messages as malformed according to verification criteria:
1. Protocol version for all protocol versions
2. ServiceType shall be equal 0x0 (Control), 0x07 (RPC), 0x0A (PCM), 0x0B (Video), 0x0F (Bulk)
3. Frame type shall be 0x00 (Control), 0x01 (Single), 0x02 (First), 0x03 (Consecutive)
4. For Control frames Frame info value shall be from 0x00 to 0x06 or 0xFE(Data Ack), 0xFF(HB Ack)
5. For Single and First frames Frame info value shall be equal 0x00
6. For Control frames Data Size value shall be less than MTU header
7. For Single and Consecutive Data Size value shall be greater than 0x00 and shall be less than N (this value will be defined in .ini file)
8. Message ID be equal or greater than 0x01 for non-Control Frames
9. Data size of First Frame shall be equal 0x08 (payload of this packet will be 8 bytes).

##### Reproduction Steps
1. Establish secure connection
2. Try to send multi-frame message with encrypted payload of the 1st frame (see p.9)

##### Expected Behavior
SDL must mark such message as malformed

##### Observed Behavior
SDL proceed with the message

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)
* Testing Against: ATF

**Comment by KVGrygoriev** [comment] 2018-08-16 09:48
Task have already done for sync4, I'll make PR here

**Comment by KVGrygoriev** [comment] 2018-08-16 15:08
Need to fix lua tests according new criteria

test_sets/dtls_encryption.txt

TOTAL: 7
PASSED: 4
FAILED: 3
5: ./test_scripts/Security/DTLS/005_Ignore_malformed_packet.lua
6: ./test_scripts/Security/DTLS/006_Ignore_unexpected_packet.lua
7: ./test_scripts/Security/DTLS/007_Processing_multiple_frames.lua
ABORTED: 0
SKIPPED: 0

**Comment by dboltovskyi** [comment] 2018-11-19 11:44
@KVGrygoriev Tests were fixed in appropriate PR

**Comment by LitvinenkoIra** [comment] 2019-12-13 11:09
Defect is reproduced.
SDL branch: feature/malformed_messages_verification (e137556)
ATF: develop
Scripts: test_sets/SDL5_0/dtls_encryption.txt (develop - 6f43bfd3)
---> 
TOTAL: 7
PASSED: 4
FAILED: 3
5: ./test_scripts/Security/DTLS/005_Ignore_malformed_packet.lua
6: ./test_scripts/Security/DTLS/006_Ignore_unexpected_packet.lua
7: ./test_scripts/Security/DTLS/007_Processing_multiple_frames.lua
ABORTED: 0
SKIPPED: 0

**Comment by LitvinenkoIra** [comment] 2019-12-13 11:10
#2516 - rebased to the latest develop
Fix is valid
SDL branch: feature/malformed_messages_verification (e137556)
ATF: develop
Scripts: test_sets/SDL5_0/dtls_encryption.txt (dboltovskyi:issue_2384 - [b86fd0a](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2146/commits/b86fd0afbd1037a5e7931c39b8dbb0810bbdcbf8))
--->
TOTAL: 6
PASSED: 6 
FAILED: 0 
ABORTED: 0 
SKIPPED: 0

**Comment by LitvinenkoIra** [comment] 2019-12-13 11:36
Need to write additional script to reproduce the issue on develop branch

**Comment by dboltovskyi** [comment] 2019-12-16 16:57
@LitvinenkoIra Additional script here couldn't be written since fix is to reduce SDL functionality to handle protected payload of 1st frame.
If this payload is protected it's size could vary.
In PR https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2146 such cases (that were originally written to check encrypted payload of 1st frame functionality) has been removed from existing scripts.

**Comment by LitvinenkoIra** [comment] 2019-12-17 14:46
@dboltovskyi Got it, thank you.

**Comment by LitvinenkoIra** [comment] 2019-12-17 14:47
@theresalech Please triage this issue

**Comment by theresalech** [comment] 2019-12-17 16:36
@LitvinenkoIra please tag me on the PR when it is ready for Livio review, thanks!

**Comment by iCollin** [comment] 2020-01-28 18:53
Closed via #2516

**Closed by iCollin** 2020-01-28 18:53 UTC
Labels: Bug, Sync4-CCB
