### ISSUE TITLE
SDL does not ignore OnVehilceData_notification  in case of receiving 'gpsData' structure with only one parameter with invalid value

### ISSUE THREAD

**Issue by AByzhynar** [smartdevicelink/sdl_core#1882] opened 2017-11-23 13:19 UTC
**Occurrence: Always** 

# Description
SDL does not ignore OnVehilceData_notification in case of receiving 'gpsData' structure
with only one parameter with invalid value

## Preconditions
1. SDL and HMI are started.
2. App is registered and activated.
3. App is subscribed for some vehicle data

## Steps to reproduce
1. HMI sends OnVehilceData_notification with 'gpsData' (and/or 'beltStatus'/ 'deviceStatus'/ 'tireStatus') structure and this structure has at least one parameter with invalid value

## Actual result
N/V

## Expected result
SDL must treat OnVehicleData_notification as invalid, log internal error and does not transfer OnVehicleData_notification to mobile app

# Environment

# Attachments
Note: Extract attached folder with script to test_scripts folder. 
[Defects.zip](https://github.com/smartdevicelink/sdl_core/files/1517714/Defects.zip)

# Expected delivery
- [ ] Source code updates
- [ ] Code comments
- [] **UTs add/update _(not required)_**
- [ ] ATF tests add/update
- [x] **Manual tests _(not required)_**
- [x] **Add/update CI plans/jobs _(not required)_**
- [x] **SDD updates _(not required)_**
- [x] **Guidelines update ([sdl_core_guides](https://github.com/smartdevicelink/sdl_core_guides)) _(not required)_**
- [x] **Guidelines update ([sdl_hmi_integration_guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines)) _(not required)_**

**Comment by aderiabin** [comment] 2017-12-01 12:24
Contributor priority is set `Low` with reason: The issue is related to notification without incorrect data.

**Comment by E-SAITO-TMC** [comment] 2020-04-20 04:38
@theresalech -san This issue is a medium priority for Toyota. I would like know if this issue occur in the latest version. And could you please include this issue in your plan? Thank you.

**Comment by theresalech** [comment] 2020-04-20 18:41
Hi @E-SAITO-TMC, we have documented that this is medium priority for Toyota, and will include for Steering Committee review and vote when planning the contents for the Q4 Core release.

@AByzhynar, can you please advise if you are seeing this issue when using Core 6.1?

**Comment by dboltovskyi** [comment] 2020-05-11 13:45
@theresalech Please notice this issue is not actual for Core 6.1.

**Comment by theresalech** [comment] 2020-05-11 15:02
Closing as not reproducible in latest version of Core.

**Closed by theresalech** 2020-05-11 15:02 UTC
Labels: Bug
